## My first practic Pytorch


## Table of Contents
* [create tensor](#)
    * [Create empty tensor](#)
    * [Create tensors with random/ones/zeros values](#)
* [operations on tensors](#)
    * [add](#)
    * [SUB](#)
    * [multiply](#)
    * [divide](#)
    * [transpose](#)
---

# create tensor

In [1]:
import torch
empty_tensor=torch.empty(2,2)
print("Empty Tensor:\n", empty_tensor)

Empty Tensor:
 tensor([[6.9874e-10, 1.1014e-42],
        [0.0000e+00, 0.0000e+00]])


# create tensors with random/ones/zeros values

In [3]:
random_tensor = torch.rand(3, 3)
ones_tensor = torch.ones(3, 3)
zeros_tensor = torch.zeros(3, 3)

print("random_tensor:\n", random_tensor)
print("ones_tensor:\n", ones_tensor)
print("zero_tensor:\n", zeros_tensor)

random_tensor:
 tensor([[0.4893, 0.7476, 0.7838],
        [0.7661, 0.6206, 0.7807],
        [0.7945, 0.7123, 0.2583]])
ones_tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
zero_tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


# operations on tensors

In [29]:
tensor_a = torch.tensor([[1,3], [2,5]])
tensor_b = torch.tensor([[1,8], [3,5]])
print("tensor_a:\n", tensor_a)
print("tensor_b:\n", tensor_b)
#added_tensors = tensor_a + tensor_b
added_tensors =torch.add(tensor_a,tensor_b)
print("\nAdded Tensors:\n", added_tensors)
#sub_tensors=tensor_a - tensor_b
sub_tensors =torch.sub(tensor_a,tensor_b)
print("\nSub Tensor:\n", sub_tensors)
#multiplied_tensors = tensor_a * tensor_b
multiplied_tensors =torch.mul(tensor_a,tensor_b) 
print("\nMultiplied Tensors:\n", multiplied_tensors)
#div_tensors=tensor_a / tensor_b
div_tensors =torch.div(tensor_a,tensor_b) 
print("\nDivided Tensors:\n", multiplied_tensors)
#transposed_tensor_a = tensor_a.T
transposed_tensor_a = torch.transpose(tensor_a,0,1)
print("\nTransposed Tensor_ a:\n", transposed_tensor_a)
#transposed_tensor_b = tensor_b.T
transposed_tensor_b = torch.transpose(tensor_b,0,1)
print("\nTransposed Tensor b:\n", transposed_tensor_b)

tensor_a:
 tensor([[1, 3],
        [2, 5]])
tensor_b:
 tensor([[1, 8],
        [3, 5]])

Added Tensors:
 tensor([[ 2, 11],
        [ 5, 10]])

Sub Tensor:
 tensor([[ 0, -5],
        [-1,  0]])

Multiplied Tensors:
 tensor([[ 1, 24],
        [ 6, 25]])

Divided Tensors:
 tensor([[ 1, 24],
        [ 6, 25]])

Transposed Tensor_ a:
 tensor([[1, 2],
        [3, 5]])

Transposed Tensor b:
 tensor([[1, 3],
        [8, 5]])
