In [1]:
import torch 
import numpy as np

# Create two random 2x2 tensors
x = torch.rand(2, 2)
y = torch.rand(2, 2)

# In-place addition of x to y
y.add_(x)
print("After in-place addition, y:\n", y)


After in-place addition, y:
 tensor([[0.3569, 1.0541],
        [0.9211, 1.4362]])


In [2]:
# Create a tensor of ones with 5 elements
first_value = torch.ones(5)
print("Initial first_value:\n", first_value)

# Convert the PyTorch tensor to a NumPy array
second_value = first_value.numpy()
print("Converted to NumPy array, second_value:\n", second_value)

# In-place addition on the original tensor
first_value.add_(1)
print("After in-place addition, first_value:\n", first_value)
# The NumPy array will also reflect the changes due to shared memory
print("NumPy array after first_value update, second_value:\n", second_value)


Initial first_value:
 tensor([1., 1., 1., 1., 1.])
Converted to NumPy array, second_value:
 [1. 1. 1. 1. 1.]
After in-place addition, first_value:
 tensor([2., 2., 2., 2., 2.])
NumPy array after first_value update, second_value:
 [2. 2. 2. 2. 2.]


In [3]:
# Create a new NumPy array of ones with 6 elements
first_value = np.ones(6)
print("New first_value (NumPy array):\n", first_value)

# Convert the NumPy array to a PyTorch tensor
second_value = torch.from_numpy(first_value)
print("Converted to PyTorch tensor, second_value:\n", second_value)

# Increment the NumPy array in-place
first_value += 1

# The tensor will also reflect the changes due to shared memory
print("Updated first_value after increment:\n", first_value)
print("Updated second_value (PyTorch tensor):\n", second_value)

New first_value (NumPy array):
 [1. 1. 1. 1. 1. 1.]
Converted to PyTorch tensor, second_value:
 tensor([1., 1., 1., 1., 1., 1.], dtype=torch.float64)
Updated first_value after increment:
 [2. 2. 2. 2. 2. 2.]
Updated second_value (PyTorch tensor):
 tensor([2., 2., 2., 2., 2., 2.], dtype=torch.float64)


In [4]:
# Check if CUDA (GPU support) is available
if torch.cuda.is_available():
    device = torch.device("cuda")
    
    # Create a tensor of ones on the GPU
    x = torch.ones(4, device=device)
    
    # Create a tensor of ones on the CPU and move it to the GPU
    y = torch.ones(4).to(device)
    
    # Perform addition on the GPU
    z = x + y
    
    # The following line would cause an error because you can't call .numpy() on a tensor on the GPU
    # z.numpy()  ## This would raise an error
    
    # You need to move the tensor back to the CPU before converting to NumPy
    z = z.to("cpu")
    print("Result moved to CPU and ready for numpy conversion:\n", z.numpy())


In [5]:
# Autograd example with forward and backward propagation
x = torch.rand(3, requires_grad=True)
print("Tensor x with requires_grad=True:\n", x)

# Perform some operations
y = x + 2
print("After operation y = x + 2:\n", y)

z = y * y * 2
print("After operation z = y^2 * 2:\n", z)

# Define a vector for the backward pass
v = torch.tensor([0.1, 0.1, 0.001], dtype=torch.float32)
# Perform the backward pass (computes the gradients)
z.backward(v)  ## dz/dx and we can call it without an argument if z is scalar
print("Gradients of x after backward pass:\n", x.grad)



Tensor x with requires_grad=True:
 tensor([0.6078, 0.6832, 0.1760], requires_grad=True)
After operation y = x + 2:
 tensor([2.6078, 2.6832, 2.1760], grad_fn=<AddBackward0>)
After operation z = y^2 * 2:
 tensor([13.6011, 14.3987,  9.4700], grad_fn=<MulBackward0>)
Gradients of x after backward pass:
 tensor([1.0431, 1.0733, 0.0087])


In [6]:
# To stop tracking the gradient for the tensor, you can use:
x.requires_grad_(False)  # OR x = x.detach()

# Detach the tensor from the computational graph (another way to stop tracking)
x = x.detach()

# To prevent gradients from being tracked, use `torch.no_grad()`
with torch.no_grad():
    x = x + 1
    print("x after operation inside torch.no_grad():\n", x)

# Corrected usage of detach
y = x.detach()
print("y (detached from x):\n", y)


x after operation inside torch.no_grad():
 tensor([1.6078, 1.6832, 1.1760])
y (detached from x):
 tensor([1.6078, 1.6832, 1.1760])
